#!/bin/bash
# ============================================
# Hook: update-sync-status.sh
# Purpose: Cap nhat sync status sau khi file duoc tao/sua
# Trigger: PostToolUse (Write|Edit)
#
# Chiến lược 2 tầng:
# - Tầng 1 (per-file): Cập nhật sync status cho file vừa write
# - Tầng 2 (full-tree): Cập nhật toàn bộ sync status và cross-validation
# ============================================

set -euo pipefail

source "$(dirname "$0")/_hook-utils.sh"
JQ_BIN=$(hook_resolve_jq || true)
TIER=$(hook_detect_tier_mode)

# ============================================
# DEPENDENCY CHECK
# ============================================

if [[ -z "$JQ_BIN" ]]; then
  echo "WARNING DEVKIT Hook: 'jq' not found. Skipping sync status update." >&2
  exit 0
fi

# ============================================
# INPUT PARSING
# ============================================

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | "$JQ_BIN" -r '.tool_name // empty' 2>/dev/null || true)
FILE_PATH=$(echo "$INPUT" | "$JQ_BIN" -r '.tool_input.file_path // empty' 2>/dev/null || true)
CONTENT=$(echo "$INPUT" | "$JQ_BIN" -r '.tool_input.new_string // .tool_input.content // empty' 2>/dev/null || true)
FILE_PATH=$(hook_normalize_path "$FILE_PATH")

if [[ -z "$FILE_PATH" ]]; then
  hook_append_metric "update-sync-status" "skipped" "missing-file-path" "" 0
  exit 0
fi

# ============================================
# FILE TYPE FILTERING
# ============================================

CODE_EXTENSIONS=(
  ".ts" ".tsx" ".js" ".jsx"
  ".py" ".java" ".cs" ".razor"
  ".go" ".rs" ".rb" ".php"
  ".swift" ".kt" ".scala"
)

IS_CODE_FILE=false
for ext in "${CODE_EXTENSIONS[@]}"; do
  if [[ "$FILE_PATH" == *"$ext" ]]; then
    IS_CODE_FILE=true
    break
  fi
done

if [[ "$IS_CODE_FILE" == false ]]; then
  hook_append_metric "update-sync-status" "skipped" "non-code-file" "$FILE_PATH" 0
  exit 0
fi

SKIP_PATTERNS=(
  "node_modules/"
  "dist/"
  "build/"
  "bin/"
  "obj/"
  ".test."
  ".spec."
  "__tests__/"
  "__pycache__/"
  ".generated."
)

for pattern in "${SKIP_PATTERNS[@]}"; do
  if [[ "$FILE_PATH" == *"$pattern"* ]]; then
    hook_append_metric "update-sync-status" "skipped" "ignored-path" "$FILE_PATH" 0
    exit 0
  fi
done

# ============================================
# REQ-ID EXTRACTION
# ============================================

REQ_IDS=$(echo "$CONTENT" | grep -oiE "REQ-([A-Z]{1,10}-)?([A-Z]{1,10}-)?([A-Z]{1,10}-)?[0-9]{3}" | tr '[:lower:]' '[:upper:]' | sort | uniq || true)

if [[ -z "$REQ_IDS" ]]; then
  hook_append_metric "update-sync-status" "skipped" "no-req-ids" "$FILE_PATH" 0
  exit 0
fi

# ============================================
# SYNC STATUS UPDATE
# ============================================

SYNC_FILE=".mc-data/sync/sync-status.md"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M")

# Initialize sync-status.md if it doesn't exist (F6: no skill creates the initial file)
if [[ ! -f "$SYNC_FILE" ]]; then
  SYNC_DIR=$(dirname "$SYNC_FILE")
  mkdir -p "$SYNC_DIR" 2>/dev/null || true
  cat > "$SYNC_FILE" <<'SYNC_INIT'
# Sync Status

> Auto-generated by update-sync-status.sh hook. Updated after each code Write/Edit.

## Summary

| Metric | Value |
|--------|-------|
| Total REQ-IDs tracked | 0 |
| Last updated | — |

## Recent Changes

SYNC_INIT
fi

if [[ "$TOOL_NAME" == "Write" ]]; then
  ACTION="Created"
else
  ACTION="Updated"
fi

if [[ -f "$SYNC_FILE" ]]; then
  for REQ_ID in $REQ_IDS; do
    TODAY=$(date "+%Y-%m-%d")
    if ! grep -q "$REQ_ID.*$TODAY" "$SYNC_FILE" 2>/dev/null; then
      if grep -q "## Recent Changes" "$SYNC_FILE"; then
        TEMP_FILE=".mc-data/tmp/sync-status-$$.tmp"
        mkdir -p ".mc-data/tmp" 2>/dev/null || true

        awk -v timestamp="$TIMESTAMP" -v req_id="$REQ_ID" -v action="$ACTION" -v file="$FILE_PATH" '
          /^## Recent Changes/ {
            print $0
            print ""
            print "### " timestamp
            print "- **" req_id "**: Code " action " in `" file "`"
            next
          }
          { print $0 }
        ' "$SYNC_FILE" > "$TEMP_FILE"

        mv "$TEMP_FILE" "$SYNC_FILE"
      fi
    fi
  done
fi

# ============================================
# SUMMARY OUTPUT
# ============================================

REQ_COUNT=$(echo "$REQ_IDS" | wc -l | tr -d ' ')
if [[ "$REQ_COUNT" -gt 0 ]]; then
  echo "DEVKIT Sync: Found $REQ_COUNT REQ-ID(s) in $FILE_PATH" >&2
fi

hook_append_metric "update-sync-status" "completed" "code-sync-update" "$FILE_PATH" "$REQ_COUNT"

exit 0
