#!/usr/bin/env bash
# Phase D GOLDEN TEST — backward-compat verify (D.9)
#
# STATUS: BLOCKED — waiting for A.3 fixture v4.1 baselines.
# Per MIGRATION-PROGRESS.md §A.3 Deferral Rationale, the 3 fixture
# folders (small-en, medium-vn, large-mixed) have structure but no
# content/baseline output yet. Baselines must be generated by running
# v4.1 legacy-scan on populated fixtures BEFORE this script can produce
# meaningful output.
#
# When A.3 is complete, run this script manually as the gate before
# tagging v5.0-phase-D. Required: 3/3 fixtures PASS.
#
# Acceptance criteria (per phase-D-agents-submigration.md §D.9):
#   - Script runs without error
#   - 3 fixtures achieve PASS verdict
#   - Feature count drift ≤ ±5% per fixture vs v4.1 baseline
#   - No invalid REQ-ID format
#   - Avg confidence ≥ v4.1 baseline (no degradation)
#   - project-context.md section count matches
#
# If FAIL: STOP, do not tag v5.0-phase-D. Investigate root cause:
#   1. Backward-compat break → fix code
#   2. Fixture variance → re-run 3× take median
#   3. Legitimate improvement (VN detection) → document exception

set -e

FIXTURES=("small-en" "medium-vn" "large-mixed")
BASELINE_DIR="docs/design/skills/wf-legacy-scan/fixtures"
RESULTS=()

echo "=== Phase D GOLDEN TEST — backward-compat verify ==="
echo

# Pre-flight: ensure baselines exist AND are populated (not just STATUS.md stub).
for fx in "${FIXTURES[@]}"; do
  BASELINE_PATH="$BASELINE_DIR/${fx}.baseline-v4.1"
  if [ ! -d "$BASELINE_PATH" ]; then
    echo "BLOCKED: fixture baseline not found at $BASELINE_PATH"
    echo "A.3 deferred parallel — run v4.1 /wf-legacy-scan on fixture, copy output here."
    echo "See MIGRATION-PROGRESS.md §A.3 Deferral Rationale."
    exit 2   # exit 2 = blocked, not a true failure
  fi
  # Empty baseline check: only STATUS.md / .gitkeep → BLOCKED
  BASELINE_FILES=$(find "$BASELINE_PATH" -type f ! -name STATUS.md ! -name '.gitkeep' 2>/dev/null | wc -l)
  if [ "$BASELINE_FILES" -eq 0 ]; then
    echo "BLOCKED: fixture baseline $BASELINE_PATH contains only STATUS.md stub."
    echo "A.3 deferred parallel — populate fixture, run v4.1 /wf-legacy-scan, copy output."
    echo "See $BASELINE_PATH/STATUS.md for populate instructions."
    exit 2
  fi
done

for fx in "${FIXTURES[@]}"; do
  echo "=== Fixture: $fx ==="
  FIXTURE_DIR="$BASELINE_DIR/$fx"
  BASELINE_PATH="$BASELINE_DIR/${fx}.baseline-v4.1"

  # Clean run v5.0 standard profile
  cd "$FIXTURE_DIR"
  rm -rf .mc-data/
  # NOTE: /wf-legacy-scan invocation here must be run by Claude Code harness
  # — this script can only prepare + verify, not drive a slash command.
  echo "  SKIP: /wf-legacy-scan invocation must be done by Claude Code."
  echo "  Populate .mc-data/ then re-run this script."
  cd - > /dev/null
  RESULTS+=("$fx: SKIP (requires /wf-legacy-scan manual invocation)")
  continue

  # Below is the verification logic, retained for reference when baselines + runs are available:
  V5_OUTPUT=".mc-data/work/legacy-scan"
  V4_BASELINE="$BASELINE_PATH"

  # Compare 1: Module count
  V5_MODULES=$(ls "$V5_OUTPUT"/classified/batch-*.json 2>/dev/null | wc -l)
  V4_MODULES=$(ls "$V4_BASELINE"/classified/batch-*.json 2>/dev/null | wc -l)

  # Compare 2: Feature count (±5% tolerance)
  V5_FEATS=$(jq -s '[.[].features // [] | length] | add' "$V5_OUTPUT"/extracted/*.json 2>/dev/null || echo 0)
  V4_FEATS=$(jq -s '[.[].features // [] | length] | add' "$V4_BASELINE"/extracted/*.json 2>/dev/null || echo 0)
  DIFF_PCT=$(awk -v a="$V5_FEATS" -v b="$V4_FEATS" 'BEGIN {if (b==0) print 0; else print (a-b)*100/b}')

  # Compare 3: Avg confidence
  V5_CONF=$(jq -s '[.[].requirements // [] | .[].confidence // 0] | add/length' "$V5_OUTPUT"/extracted/*.json 2>/dev/null)
  V4_CONF=$(jq -s '[.[].requirements // [] | .[].confidence // 0] | add/length' "$V4_BASELINE"/extracted/*.json 2>/dev/null)

  # Compare 4: project-context.md structure
  V5_SECTIONS=$(grep -c "^## " "$V5_OUTPUT"/project-context.md)
  V4_SECTIONS=$(grep -c "^## " "$V4_BASELINE"/project-context.md)

  # Compare 5: REQ-ID format consistency
  V5_IDS_BAD=$(jq -r '[.. | objects | .id? // empty] | .[]' "$V5_OUTPUT"/extracted/*.json 2>/dev/null | \
               grep -vP '^(TMP-)?(REQ|FEAT)-[A-Z]+-\d+$' | wc -l || true)

  echo "  Modules: v5=$V5_MODULES, v4=$V4_MODULES"
  echo "  Features: v5=$V5_FEATS, v4=$V4_FEATS, diff=${DIFF_PCT}%"
  echo "  Avg confidence: v5=$V5_CONF, v4=$V4_CONF"
  echo "  Sections: v5=$V5_SECTIONS, v4=$V4_SECTIONS"
  echo "  Invalid IDs: $V5_IDS_BAD"

  # Verdict
  DIFF_INT=${DIFF_PCT%.*}
  DIFF_INT=${DIFF_INT#-}  # abs value
  if [ "$DIFF_INT" -gt 5 ] 2>/dev/null; then
    echo "  FAIL: Feature count drift >5%"
    RESULTS+=("$fx: FAIL (feat drift)")
  elif [ "$V5_IDS_BAD" -gt 0 ]; then
    echo "  FAIL: $V5_IDS_BAD invalid IDs"
    RESULTS+=("$fx: FAIL (invalid IDs)")
  else
    echo "  PASS"
    RESULTS+=("$fx: PASS")
  fi
done

echo
echo "=== GOLDEN TEST SUMMARY ==="
for r in "${RESULTS[@]}"; do
  echo "  $r"
done

# Exit non-zero if any FAIL (SKIP is acceptable until A.3 complete).
for r in "${RESULTS[@]}"; do
  if [[ "$r" == *": FAIL"* ]]; then
    exit 1
  fi
done
exit 0
