# [System Name] ([system.id]) — Không có features được lập kế hoạch

> **Generated by:** `/wf-plan-modules` Phase 7.5.0 on [YYYY-MM-DD]
> **Coverage Strategy:** placeholders
> **Status:** ⚠️ ORPHAN SYSTEM — tồn tại trong registry nhưng chưa có modules/features

---

## 1. Tình trạng

System này được đăng ký trong `req-registry.json` nhưng:

- **Modules:** 0 (không có module nào có `sys_id == "[system.id]"`)
- **Features:** 0
- **Task files:** Không được tạo tự động

## 2. Thông tin System (từ registry)

- **ID:** [system.id]
- **Name:** [system.name]
- **Description:** [system.description]

## 3. Nguyên nhân có thể

1. **`/wf-analyze-requirements` chưa tạo modules cho system này** — thường xảy ra khi
   system được khai báo ở Phase 0 (brainstorm) nhưng Phase 1 analyst chưa break-down
   thành modules concrete.

2. **`/wf-define-features` chưa được chạy với scope đầy đủ** — modules đã có nhưng
   chưa có features.

3. **System này là *thin client* của system khác** — ví dụ một ERP Web Dashboard chỉ
   gọi API Backend, không có business logic riêng. Trong trường hợp này, nên dùng
   strategy `thin_clients` thay vì `placeholders`.

4. **Legacy codebase có system này nhưng chưa được reverse-engineer** — dự án legacy
   cần chạy `/wf-legacy-scan` để extract modules/features.

## 4. Hành động đề xuất

Chọn **MỘT** trong các option:

### Option A — Bổ sung modules + features

```bash
# Nếu là dự án mới / legacy chưa extract đủ:
/wf-analyze-requirements --add-system [system.id]
# hoặc đối với legacy:
/wf-legacy-extract --module [system.id]

# Sau đó:
/wf-define-features
/wf-plan-modules  # Chạy lại skill này để cập nhật coverage
```

### Option B — Chuyển sang thin client

```bash
# Chạy lại /wf-plan-modules, ở Phase 1.7 chọn option [3] MARK as thin-clients
# Ghi lý do (ví dụ: "ERP Web chỉ gọi API Backend, không có business logic riêng")
/wf-plan-modules
```

### Option C — Xóa khỏi registry

Nếu system không thực sự tồn tại trong scope dự án:
Edit `.mc-data/docs/_meta/req-registry.json` → xóa entry `systems[].[system.id]`
→ chạy lại `/wf-plan-modules`.

---

## 5. Tham chiếu

- **Registry entry:** `.mc-data/docs/_meta/req-registry.json` → `systems[]`
- **Coverage map:** `.mc-data/work/wf-plan-modules/planmod-status.json` → `system_coverage_map`
- **Module plan:** `.mc-data/docs/phase5-implementation/module-plan.md` → `## System Coverage`

> File này được tự sinh bởi `/wf-plan-modules` để ngăn "silent skip" systems trong
> phần lập kế hoạch. KHÔNG xóa file này thủ công — chạy lại `/wf-plan-modules` sau khi
> giải quyết nguyên nhân gốc để file tự cập nhật.
